// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zksdwurmgdqwybfrfhqo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inprc2R3dXJtZ2Rxd3liZnJmaHFvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0Njg1MjQsImV4cCI6MjA2NTA0NDUyNH0.NlCh0P1mOVwz_bcwo2iKqkieJ-lOGm-jwleYYvEBcb4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);